### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by mitra42** [mitra42/webForth#16]
Code has had enough changes to be worth a cleanup pass - some items to check are ....

- [x] any TODO's  - copy to issues
- [x] move logical stuff together - especially JS routines that can be deleted after replacement
- [x] Check the COLD/WARM/QUIT thinking  but see #24 
- [x] Move all constants likely to be edited together.
- [x] Make sure using whatever can of new code - e.g. vectoring EXPECT etc 
- [x] Clean out forth_v1.js
- [x] Push to Node - moved to #23 

#### README.md 
- [x] Installation instructions (depends on Node).- moved to #23 

#### DESIGN.md
- [x] Code  - moved to #25
