### ISSUE TITLE
Arduino: Meta level issues

### ISSUE THREAD

**Issue by mitra42** [mitra42/webForth#56]
I'm part way through an Arduino port - this is a list in rough order of tackling them of issues outstanding. 

Note this is all on the "#eprom" branch, and none of this works yet ! 

- [x] Complete cross-compiler (XC) output - see #57
- [x] prelim test input from cross-compiler (was too big)
- [x] Memory definitions aligned between .ino and index.js
- [x] re-test input from cross-compiler (esp sketch size) 
- [x] Move IP back from romIP as will need to traverse rom/ram
- [x] Figure out dictionary linking between rom and Ram
- [x] Check definition of Pad uses Ram (see notes in memory setup area)
- [x] Port memory setup back to Arduino - values should end up the same
- [x] Write f from jsFunctions
- [x] Output ROMSIZE and the deftn const CELLTYPE rom[ROMCELLS] PROGMEM = {...}
- [x] Output other #defs that need to be the same - e.g. NAMEE 
- [x] Rethink vHERE v, vCREATE vAllot - maybe not useful if always have code BUT also look at VARIABLE and CREATE
- [x] Make sure FORTH points to data in Ram area.
- [x] setup - needs to setup pointers from user area etc 
- [x] check tokenCreate etc - align between eprom and arduino
- [x] tokenUser's are wrong, in arduino the user offset is in cells, in "eprom" its still bytes
- [x] Dont think Arduino has "VP" as a user variable
- [x]  Rework tokenvar from EPROM branch - check branch for other changes - then merge back ramSP etc as cellSP
- [x] Argghh - cant assume that in `a(f1(), f2())` that f1() and then f2() will be called in that order.

**Comment by mitra42** [comment]
Working through vCREATE etc
: vHERE VP @ ?DUP 0= IF HERE THEN ; 
useRam - clear VP, copy to CP  
tokenVar() dereference through payload, then check for the "0" 
There is a vCREATE issue once actually defining words in RAM ... so switch back to CREATE
: vCREATE VP @ ?DUP IF tokenVar _create vALIGN , ELSE CREATE THEN ;   // Put a pointer to next cell in Ram into DIC -
: VARIABLE vCREATE CELLL vALLOT ;  // Stores address and then allocate 1 cell
vCREATE I/O 2 CELLS vALLOT TX! I/O ! RX! I/O CELLL + !   // Note doesnt initialize them.  so need to initialize after 
vCREATE 'BOOT   ' hi v, // Initializes 'BOOT with hi

- [x] Need to look at padPtr and JStoCounted

**Comment by mitra42** [comment]
Making FORTH point to something writable. 
Context and Current and Current+1 normally point to first of two data fields in Forth (or other vocabularies).  
Those fields get updated as words are created. 

Sounds like 
: VOCABULARY vCREATE 0 v, 0 v, DOES>  CONTEXT ! ;  // Which will put address of those RAM fields in CONTEXT when called
BUT how to initialize. 
UserArea will have CONTEXT pointing to FORTH but FORTH is in RAM so not initialized
OVERT does LAST @ CURRENT @ !
So could maybe do:
OVERT ( FORTH now points at most recent name) - as at UserSave 
EMPTY 
    FORTH (copy to CONTEXT)
    CONTEXT @ DUP CURRENT 2!  Current now points at Forth
Note that COLD does "EMPTY OVERT" and order shouldnt be significant

So .... surprisingly, might not require any changes except:
- [x] tokenVocabulary 
- [x] first FORTH 
- [x] start with COLD

**Comment by mitra42** [comment]
First version that works - is now up in the Eprom branch, there are some steps to do before release but it works (Including defining words in the terminal !)

**Comment by mitra42** [comment]
AFTER TESTED - i.e. command prompt and word definition working
- Go back and build the Rom area as a include file output from XC #59
- Backport - use of ramSP ramRP to eprom.index.js #60
- Any changes in index.js to arduino #60
- [x] Remove unwanted interpreter functions
- Search on TODO-ARDUINO, TODO-15-EPROM and (look for TODO-ANDROID as well, cos made that mistake at least once) #60
- [x] Search on Serial.print for debugging to comment out 
- Update README to explain how to make it work #58 
- Add to Web UI (console.html) so can dump a .ino from a web session including new definitions #61

**Comment by mitra42** [comment]
Closing as each task has own issue
