### ISSUE TITLE
META: requests from FB groups

### ISSUE THREAD

**Issue by mitra42** [mitra42/webForth#62]
I wanted one place to record requests via FB groups, mostly so I can be sure to respond when the issue is fixed.

**Comment by mitra42** [comment]
From my announcement in [Programming Forth of webForth](https://www.facebook.com/groups/PROGRAMMINGFORTH/permalink/2527022067597812)
- From Thomas Goeppel: 
    - [ ] "It's a bit slow indeed"
    - [ ] the console could need a wrap around see #89 
    - Case sensitivity - I'm a stickler for case sensitive - reserved words in upper case, because most modern languages are case sensitivity and these are string compares.
    - [x] How about I as an alias for R@?
    - [x] DO LOOP was one of the first things that users requested. see #47 
 - From Gordon Charlton
    - [ ] Safari support - see #37 
 - From Juergen Pintaske
    - Will there be a Serial Output Command, so I can send messages out and in - or even switch on LEDs in an Arduino? 
        - also asked elsewhere, and I'm not at all clear how a serial output would control a Arduino.
